[Autologin]
Relogin=false
Session=
User=

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=sddm_Random_Kipfel_Login
Font=Adwaita Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0

[Users]
MaximumUid=60513
MinimumUid=1000
